name: chronoplayer
description: "24h scheduled desktop audio player that seeks to the exact second by wall clock."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  media_kit: ^1.1.10
  media_kit_libs_linux: ^1.1.7
  system_tray: ^2.0.4
  window_manager: ^0.3.9
  shared_preferences: ^2.2.3
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/schedule.json
    - assets/audio/
